# Optional MySQL profile.
# Activate with: --spring.profiles.active=mysql
spring.datasource.url=jdbc:mysql://localhost:3306/syncslot?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
